@startuml Booking System
scale 1.5
class BookSystem {
    Rooms : List<Room>
    --
    + __init__()
    + start()
    + getRoom(String name)
    + addRoom(Room romm)
    + deleteRoom(Room romm)
    + updateRoom(String old_name,String new_name)
}
Class Room {
    id : String
    name : String
    events : List<Event>
    --
    + __init__(String _id)
    + addEvent(Event event)
    + deleteEvent(Event event)
    + modifyEvent(Event old_event,Event new_event)
}

Class Event {
    id : String
    name : String
    description: String
    start_time : DateTime
    end_time : DateTime
    participants : list<String>
    --
    + __init__(String _id)
    + addParticipant(String email)
    + deleteParticipant(String email)
    + modifyEventName(String newEventName)
    + modifyDecription(String newDescription)
    + modifyStartTime(DateTime newTime)
    + modifyEndTime(DateTime newTime)
}

'BookSystem --> Room
'Room --> Event
@enduml