@startuml
class BookSystemUI{
    + __init__()
    + initialUI()
    + runUI()
    + roomListInsert()
    + roomListDelete()
    + roomListUpdate()
    + roomListSelect()
    + ClickListBtn()
}
class BaseInterface{
    + __init__()
    + SetActive()
    + Enable()
    + Disable()
}
class BookInterface{
    + __init__()
    + Enable()
    + Disable()
    + Back()
    + SetRoomListActive()
    + UpdateRoomList()
    + CreateRoom()
    + ClickRoomButton()
    + CreateCalendarGroup()
    + SetCalendarActive()
    + ChangeDateDropDown()
    + CalculateWeek()
    + GenerateCalendar()
    + UpdateCalendar()
    + ClickCalendarButton()
    + CreateTimeLineGroup()
    + SetTimeLineActive()
    + UpdateTimeLineEvent()
    + ClickTimeLine()
    + CreateCheckBoardGroup()
    + SetCheckBoardActive()
    + UpdateLeftTime()
    + ChangeParticipantLabelDropDown()
    + AddParticipantLabelDropDown()
    + DeleteParticipantLabelDropDown()
    + CheckBoardFinish()
}
@enduml